//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJ.App.Buzzer.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SJ.App.Buzzer.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;de&quot; dir=&quot;ltr&quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///&lt;style&gt;
        ///body { 
        ///    margin:0;
        ///    padding:0;
        ///    color:#000;
        ///    background:#FFF;
        ///    font-size: 16px;
        ///    font-family:&quot;Microsoft Sans Serif&quot;,sanserif;
        ///}
        ///p, h1 {
        ///    padding:0;
        ///    margin:0 0 1em 0;
        ///}
        ///h1 {
        ///    margin-top:1.5em;
        ///    font-size:1.25em;
        ///    font-weight:bold;
        ///}
        ///&lt;/style&gt;
        ///&lt;title&gt;Info&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///&lt;p&gt;
        ///Small program to query the  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player #{0} ähnelt.
        /// </summary>
        internal static string DefaultPlayerName {
            get {
                return ResourceManager.GetString("DefaultPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;de&quot; dir=&quot;ltr&quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///&lt;style&gt;
        ///body { 
        ///    margin:0;
        ///    padding:0;
        ///    color:#000;
        ///    background:#FFF;
        ///    font-size: 16px;
        ///    font-family:&quot;Microsoft Sans Serif&quot;,sanserif;
        ///}
        ///h1 { font-size: 20px;font-weight:bold;text-align:center }
        ///h2 { font-size: 18px;font-weight:bold }
        ///&lt;/style&gt;
        ///&lt;title&gt;Lizenz&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///&lt;div&gt;
        ///Quelle und Übersetzungen: &lt;a target=&quot;_blank&quot; href=&quot;h [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F4: Start ähnelt.
        /// </summary>
        internal static string QueryStart {
            get {
                return ResourceManager.GetString("QueryStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F4: Stop ähnelt.
        /// </summary>
        internal static string QueryStop {
            get {
                return ResourceManager.GetString("QueryStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seconds for countdown? (10...600) ähnelt.
        /// </summary>
        internal static string SetupCountdown {
            get {
                return ResourceManager.GetString("SetupCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player #{0} ähnelt.
        /// </summary>
        internal static string SetupPlayerName {
            get {
                return ResourceManager.GetString("SetupPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What is the name of the player #{0}? ähnelt.
        /// </summary>
        internal static string SetupPlayerQuestion {
            get {
                return ResourceManager.GetString("SetupPlayerQuestion", resourceCulture);
            }
        }
    }
}
